
import localFont from "next/font/local";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Layout from 'antd/es/layout/layout';
import Sider from "antd/es/layout/Sider";
import { Content } from "antd/es/layout/layout";
import AppSider from "./components/AppSider";
import AppHeader from "./components/AppHeader";
import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { setUserLocale } from "./services/locale";
import { getLocale, getMessages } from 'next-intl/server';
import StoreProvider from '../lib/StoreProvider'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export  const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  setUserLocale("fr");
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
      <html lang={locale}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NextIntlClientProvider messages={messages}>
            <AntdRegistry>
              <Layout>
                <AppHeader />
                <Layout hasSider >
                  <Sider theme="light" className="fixed "  >
                    <AppSider />
                  </Sider>
                  <Layout >
                    <Content style={{ margin: 50 }} >
                      <StoreProvider>
                          {children}
                      </StoreProvider>
                    </Content>
                  </Layout>
                </Layout>
              </Layout>
            </AntdRegistry>
          </NextIntlClientProvider>
        </body>
      </html>
    
  );
}
