import localFont from "next/font/local";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Layout from 'antd/es/layout/layout';
import Sider from "antd/es/layout/Sider";
import { Content } from "antd/es/layout/layout";
import AppSider from "./components/AppSider";
import AppHeader from "./components/AppHeader";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Layout>
            <AppHeader />
            <Layout hasSider >
              <Sider theme="light" className="fixed "  >
                <AppSider />
              </Sider>
              <Layout >
                <Content style={{ margin: 50 }} >

                  {children}
                </Content>
              </Layout>
            </Layout>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
