import type { Metadata } from "next";
import localFont from "next/font/local";
import { Layout } from "antd";
import  Sider  from "antd/es/layout/Sider";
import  Content  from "antd/es/layout/layout";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";
import AppHeader from "./components/AppHeader";
import AppSider from "./components/AppSider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Layout>
            <AppHeader/>
            <Layout hasSider>
              <Sider theme="light" className="fixed " >
                <AppSider/>
              </Sider>
              <Layout >
                <Content style={{margin:50}} >

                  {children}
                </Content>
              </Layout>
            </Layout>
            </Layout>
          </AntdRegistry>
      </body>
    </html>
  );
}
